function angularAccel = AngularPointMassDynamics(bodyAngularRate, ...
                                                 moments, ...
                                                 inertia)
                                                   
% inv(inertia)*(Moments - omega x I * omega)
angularAccel            = inv(inertia)*moments+cross(bodyAngularRate,inertia*bodyAngularRate);  
