function accel = linear_acceleration(p, v, R, omega, lambda, conf)
% Get access to the system parameters
wind = conf.wind;
wingArea = conf.wingArea;
wingSpan = conf.wingSpan;
chord    = conf.chord;
mass     = conf.mass;
airDensity = conf.airDensity;
coefficients = conf.coefficients;

wind_at_altitude = awe.model.wind_at_altitude(wind, p);
[airspeed,alpha,beta] = awe.model.aerodynamic_angles(v, R, wind_at_altitude);

aero_forces_body = awe.model.aerodynamic_forces(alpha, ...
  beta, ...
  airspeed, ...
  omega, ....
  coefficients, ...
  airDensity, ...
  wingSpan, ...
  wingArea, ...
  chord);

%   tether_force = awe.model.rigid_tether_force(p, alpha,...
%                                               R, conf.tether_length, lambda, ...
%                                               airspeed, conf.airDensity, ...
%                                               conf.cableDiameter, ...
%                                               conf.dragCoefficient, ...
%                                               conf.cableDensity);

forces      = R * aero_forces_body + lambda * p;
accel    = forces / mass + conf.gravNav;